In [17]:
import array
import numpy as np
import random
import sys
from PIL import Image

# define the width  (columns) and height (rows) of your image
width = 480
height = 640

# declare 1-d array of unsigned char and assign it random values

real_img=Image.open('model.ppm')
real_img_arr=np.asarray(real_img)
real_shape=real_img_arr.shape

width=real_shape[1]
height=real_shape[0]


print(real_img_arr)
buff=array.array('B')
print(buff)

for i in range(0, width*height):
  buff.append(random.randint(0,255))

index=0
for i in range(height):
    for j in range(width):
        buff[index+j]=int((real_img_arr[i][j][0]*0.21)+(real_img_arr[i][j][0]*0.72)+(real_img_arr[i][j][0]*0.07))
    index+=width

# open file for writing 
filename = 'model.pgm'

try:
  fout=open(filename, 'wb')
except:
  print("Cannot open file “, filename, “Exiting … \n")
  sys.exit()


# define PGM Header
pgmHeader = 'P5' + '\n' + str(width) + '  ' + str(height) + '  ' + str(255) + '\n'

# write the header to the file
fout.write(pgmHeader.encode())

# write the data to the file 
buff.tofile(fout)

# close the file
fout.close()

[[[173 189 166]
  [177 191 174]
  [180 192 185]
  ...
  [153 148 140]
  [152 147 140]
  [154 149 138]]

 [[175 190 171]
  [178 192 178]
  [181 193 188]
  ...
  [153 147 139]
  [153 149 140]
  [156 150 139]]

 [[177 192 177]
  [178 191 181]
  [180 191 189]
  ...
  [155 147 141]
  [156 148 142]
  [157 151 140]]

 ...

 [[  2   7  17]
  [  2   7  17]
  [  2   7  17]
  ...
  [ 84  83  77]
  [ 83  82  76]
  [ 77  76  70]]

 [[  2   7  17]
  [  2   7  17]
  [  2   7  17]
  ...
  [ 82  81  75]
  [ 81  80  74]
  [ 75  74  68]]

 [[  2   7  17]
  [  2   7  17]
  [  2   7  17]
  ...
  [ 82  81  75]
  [ 81  80  74]
  [ 75  74  68]]]
array('B')
